openapi: "3.0.2"
info:
  title: "Backend API"
  description: "This api is created by using Express framework .Swagger is used for auto-documetation."
  version: "1.0.0"
  contact:
    name: "naim"
servers:
  - url: http://localhost:8000
paths:
  /:
    get:
      responses:
        "200":
          description: ok
  /file/upload:
    post:
      responses:
        "200":
          description: ok
        "500":
          description: Internal Server Error
        "401":
          description: Unauthorized
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      tags:
        - file
components:
  securitySchemes:
    bearAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
