version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - 27071
    volumes:
      - ./db/:/data/db
    restart: unless-stopped

  node_app:
    build: .
    ports:
      - 80:8080
    external_links:
      - "mongo"
    environment:
      - MONGO_LOCAL=mongodb://mongo:27017
      - PORT=8080
    volumes:
      - .:/app/
      - /app/node_modules
    restart: unless-stopped